const API_URL = "https://api.example.com" // Replace with your actual API URL

export const fetchCourses = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        data: [
          {
            id: 1,
            name: "Introduction to React",
            instructor: "John Doe",
            description: "Learn the basics of React development",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/react-thumbnail.jpg",
            duration: "8 weeks",
            schedule: "Tuesdays and Thursdays, 7-9 PM",
            location: "Online",
            prerequisites: ["Basic JavaScript knowledge"],
            syllabus: [
              { week: 1, topic: "React Fundamentals", content: "Introduction to React, JSX, and components" },
              { week: 2, topic: "State and Props", content: "Managing component state and props" },
            ],
          },
          {
            id: 2,
            name: "Advanced JavaScript",
            instructor: "Jane Smith",
            description: "Deep dive into advanced JavaScript concepts",
            enrollmentStatus: "In Progress",
            thumbnail: "https://example.com/js-thumbnail.jpg",
            duration: "10 weeks",
            schedule: "Mondays and Wednesdays, 6-8 PM",
            location: "Online",
            prerequisites: ["Intermediate JavaScript knowledge"],
            syllabus: [
              { week: 1, topic: "Closures and Scopes", content: "Understanding closures and lexical scope" },
              { week: 2, topic: "Asynchronous JavaScript", content: "Promises, async/await, and event loop" },
            ],
          },
          {
            id: 3,
            name: "Full Stack Web Development",
            instructor: "Alice Johnson",
            description: "Comprehensive guide to full stack development",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/fullstack-thumbnail.jpg",
            duration: "12 weeks",
            schedule: "Weekends, 10 AM - 1 PM",
            location: "Online",
            prerequisites: ["Basic HTML, CSS, and JavaScript"],
            syllabus: [
              { week: 1, topic: "Frontend Basics", content: "HTML, CSS, JavaScript review" },
              { week: 2, topic: "Backend Development", content: "Node.js and Express basics" },
            ],
          },
          {
            id: 4,
            name: "Machine Learning Fundamentals",
            instructor: "Robert Brown",
            description: "An introduction to machine learning and AI",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/ml-thumbnail.jpg",
            duration: "10 weeks",
            schedule: "Wednesdays and Fridays, 7-9 PM",
            location: "Online",
            prerequisites: ["Basic Python knowledge", "Linear Algebra"],
            syllabus: [
              { week: 1, topic: "Supervised Learning", content: "Linear regression and classification" },
              { week: 2, topic: "Unsupervised Learning", content: "Clustering and dimensionality reduction" },
            ],
          },
          
          {
            id: 5,
            name: "Cybersecurity Essentials",
            instructor: "Sarah Miller",
            description: "Learn fundamental cybersecurity concepts and best practices",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/cybersecurity-thumbnail.jpg",
            duration: "8 weeks",
            schedule: "Mondays and Wednesdays, 6-8 PM",
            location: "Online",
            prerequisites: ["Basic Networking Knowledge"],
          },
          {
            id: 6,
            name: "Cloud Computing with AWS",
            instructor: "Michael Green",
            description: "Get hands-on experience with AWS cloud services",
            enrollmentStatus: "Upcoming",
            thumbnail: "https://example.com/aws-thumbnail.jpg",
            duration: "10 weeks",
            schedule: "Tuesdays and Thursdays, 5-7 PM",
            location: "Online",
          },
          {
            id: 7,
            name: "Blockchain Development",
            instructor: "Emily White",
            description: "Explore the fundamentals of blockchain and smart contracts",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/blockchain-thumbnail.jpg",
            duration: "12 weeks",
            schedule: "Saturdays, 3-6 PM",
            location: "Online",
          },
          {
            id: 8,
            name: "DevOps Practices",
            instructor: "Kevin Taylor",
            description: "Learn continuous integration, deployment, and automation",
            enrollmentStatus: "Ongoing",
            thumbnail: "https://example.com/devops-thumbnail.jpg",
            duration: "8 weeks",
            schedule: "Fridays, 6-9 PM",
            location: "Online",
          },
          {
            id: 9,
            name: "UI/UX Design Principles",
            instructor: "Laura Adams",
            description: "Master user experience and interface design fundamentals",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/uiux-thumbnail.jpg",
            duration: "6 weeks",
            schedule: "Wednesdays, 4-6 PM",
            location: "Online",
          },
          {
            id: 10,
            name: "Python for Data Science",
            instructor: "James Wilson",
            description: "Learn Python with a focus on data analysis and visualization",
            enrollmentStatus: "Open",
            thumbnail: "https://example.com/python-thumbnail.jpg",
            duration: "8 weeks",
            schedule: "Mondays, 5-7 PM",
            location: "Online",
          },
        ],
      })
    }, 1000)
  })
}
